name: wedding
description: weddding app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #ui
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  skeleton_text: ^3.0.0
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.0
  auto_size_text: ^3.0.0
  masonry_grid: ^1.0.0
  pin_code_text_field: ^1.8.0
  simple_gradient_text: ^1.2.2
  r_dotted_line_border: ^0.1.1
  lottie: 1.2.1
  flare_flutter: ^3.0.2
  scrollable_positioned_list: ^0.2.3
  url_launcher: ^6.0.18

  #image
  file_picker: ^4.3.3
  image_picker: 0.8.4+4
  image_cropper: 1.4.1
  android_path_provider: ^0.3.0
  photo_view: ^0.13.0
  gallery_saver: ^2.3.2

  #video_player
  video_player: ^2.2.5
  video_viewer: ^1.2.0
  chewie: ^1.2.2

  #thumbnail
  video_thumbnail: ^0.4.3

  #general
  intl: ^0.17.0
  permission_handler: 8.1.4+2

  #web view
  webview_flutter: 3.0.2
  flutter_inappwebview: ^5.3.2

  #state management
  provider: ^5.0.0

  #network
  dio: ^4.0.0
  connectivity_plus: ^2.1.0
  http: ^0.13.4

  #Notification
  flutter_local_notifications: ^9.1.5
  firebase_analytics: ^8.0.2
  firebase_core: ^1.1.0
  firebase_messaging: ^11.1.0
  firebase_core_platform_interface: 4.5.1

  #local storage
  shared_preferences: ^2.0.6

  #path
  path_provider: ^2.0.8

  #cacheing
  cached_network_image: ^3.1.0
  flutter_cached_pdfview: ^0.4.1
  slide_countdown: ^0.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  gradient_borders: ^1.0.0
  badges: ^3.0.2
  fl_chart: ^0.60.0
  syncfusion_flutter_charts: ^20.4.48
  collection: ^1.16.0
  network_to_file_image: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icon_font_generator: ^3.1.0
  flutter_native_splash: ^1.3.2
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loader/
    - assets/
    - assets/fonts/
    - icons/
    - icons/black_shadow/
    - icons/white_shadow/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Hastan
      fonts:
        - asset: assets/fonts/HastanSignature.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 700
